GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "jjii",
    "name": "Jorma Jii",
    "password": "zxyzjiikl"
}

###

POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "uuno",
    "name": "Usko Uusi",
    "password": "xxy"
}
